name: mancala_game
description: Классическая игра Манкала
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/main_ico.png"
  
  adaptive_icon_background: "#5D4037" # Цвет фона как у вашей доски
  adaptive_icon_foreground: "assets/icons/main_ico.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/sounds/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/main_ico.png"