name: Mancala_WE
description: Classic Mancala game
publish_to: 'none'
version: 1.0.0+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  google_fonts: ^6.1.0
  url_launcher: ^6.3.0
  sensors_plus: ^6.1.1
  shared_preferences: ^2.2.2
  
  # google_mobile_ads: ^5.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/main_ico.png"
  
  adaptive_icon_background: "#5D4037" # Цвет фона как у доски
  adaptive_icon_foreground: "assets/icons/main_ico.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/sounds/
    - assets/audio/
    - assets/images/background.png
    - assets/images/wood_board.jpg
  fonts:
  - family: Cinzel
    fonts:
      - asset: assets/fonts/Cinzel-Bold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/main_ico.png"

